name: Electron Build for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      PYTHON: /usr/local/bin/python3  # Set PYTHON env variable globally

    steps:
    - uses: actions/checkout@v2

    - name: Debug Python path
      run: |
       echo "Python Path: $PYTHON"
       s -l /usr/bin/python*
       ls -l /usr/local/bin/python*


    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check Python installation
      run: |
        which python
        which python3
        python --version
        python3 --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel

    - name: Install npm dependencies
      run: npm install

    - name: Rebuild native modules
      run: npm run rebuild

    - name: Build Electron app for macOS
      run: |
        export PYTHON=/usr/local/bin/python3  # Explicitly set Python path
        npm run build
