name: Electron Build for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use a stable LTS version of Node.js

    - name: Set up Python
      run: export PYTHON=python3.12  # Use the correct Python version

    - name: Clean Up and Install Dependencies
      run: |
        rm -rf node_modules
        npm cache clean --force
        npm install

    - name: Build Electron app for macOS
      run: npm run build  # Use the correct script name
