name: Electron Build for macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.6.1'  # Use the correct Node.js version
    - name: Set up Python
      run: export PYTHON=python3.x  # Use the correct Python version
    - name: Install dependencies
      run: npm install
    - name: Build Electron app for macOS
      run: npm run build  # Use the correct script name
